{{- if .Values.secret.enabled -}}
{{- $passwordValue := (randAlphaNum 16) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch.uname" . }}-credentials
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  username: {{ "elastic" | b64enc }}
  {{- if .Values.secret.password }}
  password: {{ .Values.secret.password | b64enc }}
  {{- else }}
  password: {{ $passwordValue }}
  {{- end }}
{{- end }}

---


{{- if .Values.secret.enabled -}}
{{- $passwordValue := (randAlphaNum 8) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch.uname" . }}-credentials
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.secret.kibanareadonlyuser_username }}
  username: {{ .Values.secret.kibanareadonlyuser_username }}
  {{- else }}
  username: {{ "reader" | b64enc }}
  {{- end }}
  {{- if .Values.secret.kibanareadonlyuser_password }}
  password: {{ .Values.secret.kibanareadonlyuser_password | b64enc }}
  {{- else }}               
  password: {{ $passwordValue }}
  {{- end }}
  {{- if .Values.secret.kibanareadonlyuser_email }}
  email: {{ .Values.secret.kibanareadonlyuser_email }}
  {{- else }}
  email: {{ "reader@gmail.com" | b64enc }}
  {{- end }}
  {{- if .Values.secret.kibanareadonlyuser_fullname }}
  fullname: {{ .Values.secret.kibanareadonlyuser_fullname }}
  {{- else }}
  fullname: {{ "reader view" | b64enc }}
  {{- end }}
{{- end }}
